Models/Giohang.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using CLEANSHOP.Models;

namespace CLEANSHOP.Models
{
    public class Giohang
    {

        MydataDataContext data = new MydataDataContext();
        public int ID { get; set; }
                      
        [Display(Name = "Tên sản phẩm")]
        public string ProductName { get; set; }
        [Display(Name = "Ảnh bìa")]
        public string Image { get; set; }
        [Display(Name = "Đơn Giá")] 
        public Double DisPrice { get; set; }            
        [Display(Name = "Số lượng")]
        public int iSoLuong { get; set; }
        public int soluongton { get; set; }

        [Display(Name = "Thành tiền")]
        public Double TotalPrice
        {
            get { return iSoLuong * DisPrice; }
        }

        public Giohang(int  id)
        {
             ID = id;
             Product product = data.Products.Single(n => n.Id ==id);
            ProductName = product.ProductName;
            Image = product.Image;
            DisPrice = double.Parse(product.DisPrice.ToString());
            iSoLuong = 1;
            soluongton = int.Parse(product.Amount.ToString());
        }

        
     
    }
}

Controllers/DichVuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CLEANSHOP.Models;
using PagedList;

namespace CLEANSHOP.Controllers
{
    public class DichVuController : Controller
    {
        // GET: DichVu
        MydataDataContext data = new MydataDataContext();

        public ActionResult Index(int? page, string searchString)
        {
            if (page == null) page = 1;

            var all_product = (from tt in data.Products select tt).OrderBy(m => m.Id);
            if (!string.IsNullOrEmpty(searchString)) all_product = (IOrderedQueryable<Product>)all_product.Where(a => a.ProductName.Contains(searchString));
            int pageSize = 6;
            int pageNum = page ?? 1;

            return View(all_product.ToPagedList(pageNum, pageSize));
        }
        public ActionResult Sanpham(int? page)
        {
            if (page == null) page = 1;

            var all_product = (from tt in data.Products select tt).OrderBy(m => m.Id);
            int pageSize = 100;
            int pageNum = page ?? 1;

            return View(all_product.ToPagedList(pageNum, pageSize));
        }

        public ActionResult Detail(int id)
        {
            var D_Products = data.Products.Where(m => m.Id == id).First(); return View(D_Products);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(FormCollection collection, Product s)
        {

            var E_ProductName = collection["ProductName"];
            var E_Image = collection["Image"];
            var E_Detail = collection["Detail"];
            var E_Time = collection["Time"];
            var E_Text = collection["Text"];

            var E_Price = Convert.ToDecimal(collection["Price"]);
            var E_Amount = Convert.ToInt32(collection["Amount"]);

            // var E_ngaycapnhat = Convert.ToDateTime(collection["ngaycapnhat"]);
            // var E_soluongton Convert.ToInt32(collection["soluongton"]);
            if (string.IsNullOrEmpty(E_ProductName))

            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                s.ProductName = E_ProductName.ToString();
                s.Image = E_Image.ToString();
                s.Detail = E_Detail.ToString();

                s.Text = E_Text.ToString();
                s.Price = E_Price;
                s.Amount = E_Amount;
                s.DisPrice = E_Price;
                s.DisCount = 1.0;
                //   s.ngaycapnhat = E_ngaycapnhat;
                //  s.soluongton = E_soluongton;
                data.Products.InsertOnSubmit(s);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Create();
        }


        public ActionResult Edit(int id)
        {
            var E_Products = data.Products.First(m => m.Id == id);
            /*    List<SelectListItem> discountList = new List<SelectListItem>();// set discount list
                discountList.Add(new SelectListItem { Text = "No Discount", Value = "1" });
                discountList.Add(new SelectListItem { Text = "10%", Value = "0,9" });
                discountList.Add(new SelectListItem { Text = "20%", Value = "0,8" });
                discountList.Add(new SelectListItem { Text = "50%", Value = "0,5" });
                ViewBag.Discount = discountList;*/
            return View(E_Products);
        }
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            var E_Products = data.Products.First(m => m.Id == id);
            var E_ProductName = collection["ProductName"];
            var E_Image = collection["Image"];
            var E_Detail = collection["Detail"];

            var E_Text = collection["Text"];
            var E_Amount = Convert.ToInt32(collection["Amount"]);
            var E_Price = Convert.ToDecimal(collection["Price"]);
            var E_Discount = Convert.ToDouble(collection["DisCount"]);
            var E_DisPrice = Convert.ToDecimal(collection["Price"]) * Convert.ToDecimal(collection["DisCount"]);
            //var E_ngaycapnhat = Convert.ToDateTime(collection["ngaycatnhat"]);
            //  var E_soluongton = Convert.ToInt32(collection["soluongton"]);
            E_Products.Id = id;
            if (string.IsNullOrEmpty(E_ProductName))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else

            {
                E_Products.ProductName = E_ProductName;
                E_Products.Image = E_Image;
                E_Products.Detail = E_Detail;

                E_Products.Text = E_Text;
                E_Products.Amount = E_Amount;
                E_Products.Price = E_Price;
                E_Products.DisCount = E_Discount;
                E_Products.DisPrice = E_DisPrice;
                // E_Products.ngaycapnhat = E_ngaycapnhat;
                // E_Products.soluongton = E_soluongton;
                UpdateModel(E_Products);
                data.SubmitChanges();
                return RedirectToAction("ListSach");
            }
            return this.Edit(id);
        }

        public string ProcessUpload(HttpPostedFileBase file)
        {
            if (file == null)
            {
                return "";
            }
            file.SaveAs(Server.MapPath("~/Content/Images/" + file.FileName));
            return "/Content/Images/" + file.FileName;
        }

        public ActionResult Delete(int id)
        {
            var E_Products = data.Products.First(m => m.Id == id);

            return View(E_Products);
        }
        [HttpPost]

        public ActionResult Delete(int id, FormCollection collection)
        {


            var E_Products = data.Products.First(m => m.Id == id);
            var E_ProductName = collection["ProductName"];
            var E_Image = collection["Image"];
            var E_Detail = collection["Detail"];

            var E_Text = collection["Text"];
            var E_Amount = Convert.ToInt32(collection["Amount"]);
            var E_Price = Convert.ToDecimal(collection["Price"]);
            var E_Discount = Convert.ToDouble(collection["DisCount"]);
            var E_DisPrice = Convert.ToDecimal(collection["Price"]) * Convert.ToDecimal(collection["DisCount"]);
            //var E_ngaycapnhat = Convert.ToDateTime(collection["ngaycatnhat"]);
            //var E_soluongton = Convert.ToInt32(collection["soluongton"]);
            E_Products.Id = id;
            if (string.IsNullOrEmpty(E_ProductName))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else

            {
                E_Products.ProductName = E_ProductName;
                E_Products.Image = E_Image;
                E_Products.Detail = E_Detail;

                E_Products.Text = E_Text;
                E_Products.Amount = E_Amount;
                E_Products.Price = E_Price;
                E_Products.DisCount = E_Discount;
                E_Products.DisPrice = E_DisPrice;
                //E_Products.ngaycapnhat = E_ngaycapnhat;
                //E_Products.soluongton = E_soluongton;
                UpdateModel(E_Products);
                data.SubmitChanges();
                return RedirectToAction("ListSach");
            }
            return this.Delete(id);


        }
        public ActionResult ListSach()
        {


            Customer kh = (Customer)Session["Taikhoan"];
            if (Session["Taikhoan"] == null)
            {
                return RedirectToAction("XacNhanAdmin", "GioHang");

            }
            else
            {
                if (kh.limit == 1)
                {
                    var all_product = from ss in data.Products select ss;
                    return View(all_product);
                }
                else
                    return RedirectToAction("XacNhanAdmin", "GioHang");
            }

            return View();

        }

        public ActionResult Nhom()
        {
            return PartialView();
        }


        public ActionResult Category()
        {
            return PartialView();
        }
        public ActionResult LoaiSanPham()
        {
            var loaisanpham = from s in data.Types select s;
            return PartialView(loaisanpham);
        }
        public ActionResult DanhMuc()
        {
            var loaisanpham = from s in data.Types select s;
            return PartialView(loaisanpham);
        }

        public ActionResult SPTheoLoai(int id)
        {
            var sptl = from ss in data.Products where ss.ID_Type == id select ss;
            return PartialView(sptl);

        }

        public ActionResult DonHang()
        {

            var dh = from ss in data.Carts select ss;
            var tt = data.Carts.Sum(n => Convert.ToInt32(n.TotalPrice));
            ViewBag.tongtien = tt;
            return View(dh);
                
        }

        public ActionResult Chitiet(int id)
        {
            List<CartDetail> chitiet = data.CartDetails.Where(m => m.IdCart == id).ToList();
            return View(chitiet);
        }
        public ActionResult DeleteDH(int id)
        {
            var E_Cart = data.Carts.First(m => m.IdCart == id);

            return View(E_Cart);
        }
       
            [HttpPost]
            public ActionResult DeleteDH(int id, FormCollection collection)
            {
                var D_giay = data.Carts.Where(m => m.IdCart== id).First();          
                data.Carts.DeleteOnSubmit(D_giay);
            var D_Dtail = data.CartDetails.Where(m => m.IdCart == id).First();
                 data.CartDetails.DeleteOnSubmit(D_Dtail);
            data.SubmitChanges();
                return RedirectToAction("ListSach");
            }


        }
    }
   




    

Controllers/momoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json.Linq;
using System.IO;
using CLEANSHOP.Others;
using CLEANSHOP.Models;

namespace CLEANSHOP.Controllers
{
    public class momoController : Controller
    {
        // GET: momo
        public ActionResult Index()
        {
            return View();
        }
        private double TongTien()
        {
            double tt = 0;
            List<Giohang> lstGiohang = Session["GioHang"] as List<Giohang>;
            if (lstGiohang != null)
            {
                tt = lstGiohang.Sum(n => n.TotalPrice);
            }

            if (tt <= 300000)
            {
                return tt;
            }
            else
            {
                if (tt > 300000 && tt <= 500000)
                {
                    return tt * 0.7;
                }
                else
                {
                    return tt * 0.5;
                }
            }
        }

        public ActionResult Payment()
        {
            Customer kh = (Customer)Session["Taikhoan"];
            
            //request params need to request to MoMo system
            string endpoint = "https://test-payment.momo.vn/gw_payment/transactionProcessor";
            string partnerCode = "MOMOHNZA20220411";
            string accessKey = "R5L1OkfJdROk6ysv";
            string serectkey = "HkGHZa9JmvfapaC7cWKIYo4kUolj7Qoo";
            string orderInfo = kh.Name.ToString();
            string returnUrl = "https://localhost:44394/Home/ConfirmPaymentClient";
            string notifyurl = "http://ba1adf48beba.ngrok.io/Home/SavePayment"; //lưu ý: notifyurl không được sử dụng localhost, có thể sử dụng ngrok để public localhost trong quá trình test

            string amount = TongTien().ToString();
            string orderid = DateTime.Now.Ticks.ToString();
            string requestId = DateTime.Now.Ticks.ToString();
            string extraData = "";

            //Before sign HMAC SHA256 signature
            string rawHash = "partnerCode=" +
                partnerCode + "&accessKey=" +
                accessKey + "&requestId=" +
                requestId + "&amount=" +
                amount + "&orderId=" +
                orderid + "&orderInfo=" +
                orderInfo + "&returnUrl=" +
                returnUrl + "&notifyUrl=" +
                notifyurl + "&extraData=" +
                extraData;

            MoMoSecurity crypto = new MoMoSecurity();
            //sign signature SHA256
            string signature = crypto.signSHA256(rawHash, serectkey);

            //build body json request
            JObject message = new JObject
            {
                { "partnerCode", partnerCode },
                { "accessKey", accessKey },
                { "requestId", requestId },
                { "amount", amount },
                { "orderId", orderid },
                { "orderInfo", orderInfo },
                { "returnUrl", returnUrl },
                { "notifyUrl", notifyurl },
                { "extraData", extraData },
                { "requestType", "captureMoMoWallet" },
                { "signature", signature }

            };

            string responseFromMomo = PaymentRequest.sendPaymentRequest(endpoint, message.ToString());

            JObject jmessage = JObject.Parse(responseFromMomo);

            return Redirect(jmessage.GetValue("payUrl").ToString());
           
        }

        //Khi thanh toán xong ở cổng thanh toán Momo, Momo sẽ trả về một số thông tin, trong đó có errorCode để check thông tin thanh toán
        //errorCode = 0 : thanh toán thành công (Request.QueryString["errorCode"])
        //Tham khảo bảng mã lỗi tại: https://developers.momo.vn/#/docs/aio/?id=b%e1%ba%a3ng-m%c3%a3-l%e1%bb%97i
        public ActionResult ConfirmPaymentClient()
        {
            //hiển thị thông báo cho người dùng
            return View();
        }

        [HttpPost]
        public void SavePayment()
        {
            //cập nhật dữ liệu vào db
        }
    }

}

Views/GioHang/DatHang.cshtml
@model IEnumerable<CLEANSHOP.Models.Giohang>

@{
    ViewBag.Title = "DatHang";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Đặt hàng</h2>
@Html.BeginForm("DatHang","GioHang", FormMethod.Post){
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DisPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.iSoLuong)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalPrice)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td> @Html.DisplayFor(modelItem => item.ProductName) </td>
            <td> <img src="@item.Image" width="180" /> </td>
            @using (Html.BeginForm("CapnhatGiohang", "GioHang", new { @id = item.ID }))
            {
                <td> @string.Format("{0:0,0}", item.DisPrice) VNĐ </td>
                <td>
                    <input type="number" min="1" name="txtSoLg"
                           value="@item.iSoLuong" />
                </td>
                <td> @Html.DisplayFor(modelItem => item.TotalPrice) </td>
                <td>
                    <a href="@Url.Action("Detail", "DichVu", new { id = item.ID })">
                        Chi
                        tiết
                    </a> | @Html.ActionLink("Xóa", "XoaGiohang", new { @id = item.ID })
                </td>
                <td>
                    <input type="submit" value="Cập nhật" class="btn btn-success" />
                </td>
            }
        </tr>
    }
    <tr style="font-weight:bold; text-align:left; color:red">
        <td colspan="2"> Số loại sản phẩm: @ViewBag.Tongsoluongsanpham </td>
        <td colspan="2"> số lượng sản phẩm: @ViewBag.Tongsoluong </td>
        <td colspan="4">

            @if (ViewBag.TongTien <= 300000)
            {
                <p colspan="4">Tổng tiền:</p>
                <p> @String.Format("{0:0,0}", ViewBag.Tongtien) VND</p>
            }
            else
            {
                if (ViewBag.TongTien > 300000 && ViewBag.TongTien <= 500000)
                {
                    <p colspan="4">Tổng tiền:</p>
                    <p style=" text-decoration-line:line-through"> @String.Format("{0:0,0}", ViewBag.Tongtien) VND</p>
                    <p colspan="4">Giảm giá còn:</p>
                    <p> @String.Format("{0:0,0}", ViewBag.TienGiam1) vnd </p>
                }
                else
                {
                    <p colspan="4">Tổng tiền:</p>
                    <p style=" text-decoration-line:line-through"> @String.Format("{0:0,0}", ViewBag.Tongtien) VND</p>
                    <p colspan="4">Giảm giá còn:</p>
                    <p> @String.Format("{0:0,0}", ViewBag.TienGiam2) VND </p>
                }

            }
        </td>
    </tr>
    <tr style="font-weight:bold; text-align:right">
        <td colspan="6">@Html.ActionLink("Trở về giỏ hàng", "Giohang", "GioHang")</td>
    </tr>
    <tr style="font-weight:bold; color:blue; text-align:right ">
        <td colspan="6">
            @Html.ActionLink("Xóa giỏ hàng", "XoaTatCaGioHang")
        </td>
    </tr>
    <tr style="font-weight:bold; color:yellow; text-align:right ">
        <td colspan="6">
            <button class="btn btn-info">  @Html.ActionLink("Đặt hàng", "Dathang", "GioHang") </button>
        </td>

    </tr>
</table>

@using CLEANSHOP.Models
<h2 style-"text-align:center">Thông tin đặt hàng</h2>
@{ Customer kh = (Customer)Session["TaiKhoan"]; }
<table align-"center">
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        <tr style="height:40px">
            <td>Họ tên : </td>
            <td style="font-weight:bold">@kh.Name</td>
        </tr>
        <tr style="height:40px">
            <td>Email: </td>
            <td style="font-weight:bold">@kh.Email</td>
        </tr>
        <tr style="height:40px">
            <td>Địa chỉ: </td>
            <td style-"font-weight:bold">@kh.Address</td>
        </tr>
        <tr style="height:40px">
            <td>Điện thoại: </td>
            <td style="font-weight:bold">@kh.Phone</td>
        </tr>
        <tr style="height:40px">
            <td>Ngày đặt: </td>
            <td style="font-weight:bold">@DateTime.Now.ToShortDateString()</td>
        </tr>
        <tr style="height:40px">
            <td>Ngày giao: </td>
            <td style="font-weight:bold">
                <input type="date" id=" booking" name="BookingDate" />
                @ViewData["checkngay"]
            </td>
        </tr>
        <tr style="height:40px">
            <td></td>
            <td style="font-weight:bold">
                @*<a value="Xác nhận" class="btn btn-success" href="@.Action("DatHang","GioHang")">Thanh toán truc tiep </a>*@
                <input type="submit" id=" btnDatHang" class="btn btn-success" value="Thanh toán truc tiep" />

                <a href="@Url.Action("Payment","momo")">Thanh toán bằng MOMO</a>
            </td>
        </tr>
    }
</table>


@*<script>
    document.getElementById("btnDatHang").onclick = function (e) {
        var selectedDate = document.getElementById("booking").value;
        if (!Date.parse(selectedDate)) {
            Swal.fire({
                title: 'Thông báo',
                text: 'Vui lòng chọn ngày giao hàng!',
                icon: 'error',
            })
            e.preventDefault();
        }
        if (Date.parse(selectedDate) < Date.now()) {
            Swal.fire({
                title: 'Thông báo',
                text: 'Ngày giao hàng phải lớn hơn hiện tại!',
                icon: 'error',
            })
            e.preventDefault();
        }
    }
</script>*@

Views/GioHang/GioHang.cshtml
@model IEnumerable<CLEANSHOP.Models.Giohang>

@{
    ViewBag.Title = "GioHang";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<section class="vh-100">
    <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col">
                <p><span class="h2">Shopping Cart </span><span class="h4">(@ViewBag.Tongsoluongsanpham loại sản phẩm đang có trong giỏ hàng)</span></p>
                @foreach (var item in Model)
                {
                    <div class="card mb-4">
                        <div class="card-body p-4">

                            <div class="row align-items-center">
                                <div class="col-md-2">
                                    <img src="@item.Image" class="img-fluid" alt="Generic placeholder image" width="100%">
                                </div>
                                <div class="col-md-2 d-flex justify-content-center">
                                    <div>
                                        <p class="small text-muted mb-4 pb-2"> @Html.DisplayNameFor(model => model.ProductName)</p>
                                        <p class="lead fw-normal mb-0"> @Html.DisplayFor(modelItem => item.ProductName)</p>
                                    </div>
                                </div>
                                <div class="col-md-2 d-flex justify-content-center">
                                    <div>
                                        <p class="small text-muted mb-4 pb-2"> @Html.DisplayNameFor(model => model.DisPrice)</p>
                                        <p class="lead fw-normal mb-0">
                                            @String.Format("{0:0,0}", item.DisPrice) VNĐ
                                        </p>
                                    </div>
                                </div>
                                <div class="col-md-2 d-flex justify-content-center">
                                    <div>
                                        <p class="small text-muted mb-4 pb-2"> @Html.DisplayNameFor(model => model.iSoLuong)</p>
                                        <p class="lead fw-normal mb-0">
                                            <input type="number" min="1" max="@item.soluongton" name="txtSoLg"
                                                   value="@item.iSoLuong" style="border:none; width:50px;" />
                                        </p>
                                    </div>
                                </div>
                                <div class="col-md-2 d-flex justify-content-center">
                                    <div>
                                        <p class="small text-muted mb-4 pb-2"> @Html.DisplayNameFor(model => model.TotalPrice)</p>
                                        <p class="lead fw-normal mb-0"> @Html.DisplayFor(modelItem => item.TotalPrice)</p>
                                    </div>
                                </div>
                                <div class="col-md-2 d-flex justify-content-center">
                                    <div>
                                        <a href="@Url.Action("Detail", "DichVu", new { @id = item.ID })">
                                            Chi tiết
                                        </a> | @Html.ActionLink("Xóa", "XoaGiohang", new { @id = item.ID })
                                    </div>
                                </div>
                                <div class="col-md-2 d-flex justify-content-end">
                                    <div>
                                        <input type="submit" value="Cập nhật" class="btn btn-success" />
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <hr />
                }
                <div style="background:white;  text-align:right; width:100%; display:flex; justify-content:space-between;">
                    <h4 style="padding:10px;"> Số loại sản phẩm : @ViewBag.Tongsoluongsanpham </h4>
                    <h4 style="padding:10px;"> Số lượng sản phẩm: @ViewBag.Tongsoluong </h4>
                    <div style="padding:10px; ">
                        <h4 style="display:flex;">
                            @if (ViewBag.TongTien <= 300000)
                            {
                                <p colspan="4">Tổng tiền:</p>
                                <p> @String.Format("{0:0,0}", ViewBag.Tongtien) <span>vnđ</span></p>
                            }
                            else
                            {
                                if (ViewBag.TongTien > 300000 && ViewBag.TongTien <= 500000)
                                {
                                    <p colspan="4">Tổng tiền:</p>
                                    <p style=" text-decoration-line:line-through"> @String.Format("{0:0,0}", ViewBag.Tongtien) VND</p>
                                    <p colspan="4">Giảm Giá:</p>
                                    <p> @String.Format("{0:0,0}", ViewBag.TienGiam1) VND </p>
                                }
                                else
                                {
                                    <p colspan="4">Tổng tiền:</p>
                                    <p style=" text-decoration-line:line-through"> @String.Format("{0:0,0}", ViewBag.Tongtien) VND</p>
                                    <p colspan="4">Giảm Giá:</p>
                                    <p> @String.Format("{0:0,0}", ViewBag.TienGiam2) VND </p>
                                }

                            }
                        </h4>
                    </div>

                </div>
                <div class="d-flex justify-content-end">
                    <div style="margin:50px; display :flex; justify-content:center;  ">

                        <a class="btn btn-success" style="margin-right:40px;"
                           href=@Url.Action("Dathang", "GioHang")> ĐẶT HÀNG </a>
                        <a class="btn btn-danger"
                           href=@Url.Action("XoaTatCaGioHang", "GioHang")>Xóa tất cả</a>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>

@*<tr style="font-weight: bold; text-align:left; color:red">
        <td colspan="2"> Số loại sản phẩm : @ViewBag.Tongsoluongsanpham </td>
        <td colspan="2"> Số lượng sản phẩm: @ViewBag.Tongsoluong </td>
        <td colspan="4">
            Tổng tiền: @String.Format("{0:0,0}", @ViewBag.Tongtien) VNĐ
        </td>
    </tr>
    <tr style="font-weight:bold; color:blue; text-align:right ">
        <td colspan="5">
            @Html.ActionLink("Xóa giỏ hàng", "XoaTatCaGioHang")
        </td>
    </tr>*@

Views/GioHang/GioHangPartial.cshtml
@using CLEANSHOP.Models
@{
    List<Giohang> lstgiohang = Session["GioHang"] as List<Giohang>;
}




@if (Session["GioHang"] != null)
{
    <a class="getstarted scrollto active" href="@Url.Action("miniGiohang", "GioHang")" style="font-weight:bold;text-decoration:none; color:black">
        <i class="fa-solid fa-cart-shopping"> @lstgiohang.Count()</i> 

    </a>
}

Views/GioHang/Ten.cshtml
@using CLEANSHOP.Models
@{
    Customer kh = (Customer)Session["TaiKhoan"];
}
<a class="getstarted scrollto active" href="@Url.Action("profile","NguoiDung",new { @id = kh.IdCustomer})" style="text-decoration:none;color:#000">
    Tên     : @kh.Name
</a>

Views/GioHang/XacNhanAdmin.cshtml
@{
    ViewBag.Title = "XacnhanAdmin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Xin thông báo ! </h1>
<h2>Mục này chỉ dành cho admin, mong quý khách thông cảm cho sự bất tiện này !!!</h2>

<p>
    @Html.ActionLink("Về trang chủ", "Index", "DichVu")
</p>

Views/GioHang/XacNhanDonHang.cshtml
@{
    ViewBag.Title = "XacnhanDonHang";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Ðơn hàng đã được xác nhận</h2>
<h3>Chúng tôi sẽ giao hàng cho bạn sớm nhất có thể !</h3>
@*<div class="img" >
    <img src="" alt="Alternate Text" />
</div>*@
<p>
    @Html.ActionLink("Về trang chủ", "Index", "DichVu")
</p>