Controllers/NguoiDungController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using CLEANSHOP.Models;
using Facebook;

namespace CLEANSHOP.Controllers
{
    public class NguoiDungController : Controller
    {
        MydataDataContext data = new MydataDataContext();
        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Dangky(FormCollection collection, Customer kh)
        {


            var Name = collection["Name"];
            var LoginName = collection["LoginName"];
            var Password = collection["Password"];
            var ConfirmPassword = collection["ConfirmPassword"];
            var Email = collection["Email"];
            var Address = collection["Address"];
            var Phone = collection["Phone"];
            var limit = Convert.ToInt32(collection["limit"]);
            var DateofBirth = String.Format("{0:MM/dd/yyyy}", collection["DateofBirth"]);



            if (String.IsNullOrEmpty(ConfirmPassword))
                ViewData["NhapMKXN"] = "Phải nhập đủ thông tin!";
            else if (String.IsNullOrEmpty(Name))
                ViewData["NhapHoten"] = "Phải nhập đủ họ tên";
            else if (String.IsNullOrEmpty(Phone))
                ViewData["nhapDT"] = "Phải nhập số điện thoại";
            else if (String.IsNullOrEmpty(Address))
                ViewData["nhapDC"] = "Phải nhập địa chỉ";
            else if (String.IsNullOrEmpty(Email))
                ViewData["nhapEmail"] = "Phải nhập Email";
            else if (String.IsNullOrEmpty(LoginName))
                ViewData["NhapTK"] = "Phải nhập tên đăng nhập";
            else if (String.IsNullOrEmpty(Password))
                ViewData["nhapMK"] = "Phải nhập mật khẩu";
            else if (Password.Length > 8)
                ViewData["dodaiMK"] = "mật khẩu phải nhiều hơn 8 ký tự";

            else if (String.IsNullOrEmpty(Password))
                ViewData["nhapMK"] = "Phải nhập mật khẩu";
            else if (String.IsNullOrEmpty(DateofBirth))
                ViewData["nhapNS"] = "Phải nhập ngày sinh";
            else
            {
                if (!Password.Equals(ConfirmPassword))
                {
                    ViewData["MatKhauGiongNhau"] = "Mật khẩu và mật khẩu xác nhận phải giống nhau";
                }
                else
                {
                    kh.Name = Name;
                    kh.LoginName = LoginName;
                    kh.Password = Password;
                    kh.Email = Email;
                    kh.Address = Address;
                    kh.Phone = Phone;
                    kh.limit = limit;
                    kh.DateofBirth = DateTime.Parse(DateofBirth);
                    data.Customers.InsertOnSubmit(kh);
                    data.SubmitChanges();
                    return RedirectToAction("DangNhap");
                }
            }
            return this.DangKy();
        }












        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangNhap(FormCollection collection)
        {
            var LoginName = collection["LoginName"];
            var Password = collection["Password"];
            var limit = Convert.ToInt32(collection["limit"]);
            Customer kh = data.Customers.SingleOrDefault(n => n.LoginName == LoginName && n.Password == Password && n.limit >= 0);
            if (kh != null)
            {
                ViewBag.ThongBao = "Chúc mừng đăng nhập thành công";
                Session["Taikhoan"] = kh;
                return RedirectToAction("Index", "DichVu");
            }
            else
            {
                ViewBag.ThongBao = "Tên đăng nhập hoặc mật khẩu không đúng";
            }
           
            return View();
        }
       


        public ActionResult DangXuat()
        {
            Session.Clear();
            return RedirectToAction("DangNhap");
        }


        public JsonResult CheckUsername(string userdata)
        {
            System.Threading.Thread.Sleep(200);
            var SearchData = data.Customers.Where(x => x.LoginName == userdata).SingleOrDefault();

            if (SearchData != null)
            {
                return Json(1);
            }
            else
            {
                return Json(0);
            }
        }

        public JsonResult CheckEmail(string userdata)
        {
            System.Threading.Thread.Sleep(200);
            var SearchData = data.Customers.Where(x => x.Email == userdata).SingleOrDefault();

            if (SearchData != null)
            {
                return Json(1);
            }
            else
            {
                return Json(0);
            }
        }

       public JsonResult CheckPhone(string userdata)
        {
            System.Threading.Thread.Sleep(200);
            var SearchData = data.Customers.Where(x => x.Phone == userdata).SingleOrDefault();

            if (SearchData != null)
            {
                return Json(1);
            }
            else
            {
                return Json(0);
            }
        }

        private double TongTien()
        {
            double tt = 0;
            List<Giohang> lstGiohang = Session["GioHang"] as List<Giohang>;
            if (lstGiohang != null)
            {
                tt = lstGiohang.Sum(n => n.TotalPrice);
            }

            if (tt <= 300000)
            {
                return tt;
            }
            else
            {
                if (tt > 300000 && tt <= 500000)
                {
                    return tt * 0.7;
                }
                else
                {
                    return tt * 0.5;
                }
            }
        }


        public ActionResult sendPass(string pass, System.Web.Mvc.FormCollection collection)

        {
           Cart dh = new Cart();
           Customer kh = (Customer)Session["Taikhoan"];

          /*  var ngaygiao = String.Format("{0:MM/dd/yyyy}", collection["NgayGiao"]);*/
            dh.BookingDate = DateTime.Now;
           

            MailAddress fromAddress = new MailAddress("binhminh220901@gmail.com", "PHỤ KIỆN GIÀY AK2M");

            MailAddress toAddress = new MailAddress(kh.Email.ToString());

            const string fromPassword = "ipzzdyzcoriefohw";

            string subject = "Xác nhận đơn hàng";

            string Tien = TongTien().ToString();

            string Soluong = TongSoLuongSanPham().ToString();

            string Ten = kh.Name.ToString();

            string NgayDat = dh.BookingDate.ToString();

            string madh = dh.IdCart.ToString();


            SmtpClient smtp = new SmtpClient

            {

                Host = "smtp.gmail.com",

                Port = 587,

                EnableSsl = true,

                DeliveryMethod = SmtpDeliveryMethod.Network,

                UseDefaultCredentials = false,

                Credentials = new NetworkCredential(fromAddress.Address, fromPassword)

            };

            using (MailMessage message = new MailMessage(fromAddress, toAddress)

            {

                Subject = subject,

                Body =

                        "<p>Xác nhận đơn hàng gồm : </p>" +
                         "<p>Số lượng sản phẩm :  " + Soluong + " sản phẩm  </p>" +
                         "<p>Tên KH : " + Ten + "   </p>" +
                          "<p>Email : " + kh.Email.ToString() + "   </p>" +
                         "<p color = red>Tổng thành tiền : " + Tien + " VND  </p>"
                        + "<p>Ngày đặt hàng  :" + NgayDat + "</p>"
                        + "<p>Mã đơn hàng  : " + madh + "</p>" +
                        "<button> Xác nhận đơn hàng </Button>",

                IsBodyHtml = true,

            })

            {

                smtp.Send(message);
                return RedirectToAction("DatHang","GioHang");
            }
            
        }



       
        private int TongSoLuongSanPham()
        {
            int tsl = 0;
            List<Giohang> lstGiohang = Session["GioHang"] as List<Giohang>;
            if (lstGiohang != null)
            {
                tsl = lstGiohang.Count;
            }
            return tsl;
        }
        
        public ActionResult profile(int id)
        {
            Customer kh = (Customer)Session["Taikhoan"];
            
            var E_Pro = data.Customers.First(m => m.IdCustomer == id);
            return View(E_Pro);
        }
        [HttpPost]
        public ActionResult profile(int id, FormCollection collection)
        {
            Customer kh = (Customer)Session["Taikhoan"];

            var E_Pro = data.Customers.First(m => m.IdCustomer == id);

            var hoten = collection["Name"];
            var tendangnhap = collection["LoginName"];
            var matkhau = collection["Password"];
            var MatkhauXacNhan = collection["MatKhauXacNhan"];
            var email = collection["Email"];
            var diachi = collection["Address"];
            var dienthoai = collection["Phone"];
            var ngaysinh = String.Format("{0:MM/dd/yyyy}", collection["DateofBirth"]);

           
            if (string.IsNullOrEmpty(hoten))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {

                kh.LoginName = tendangnhap;
                kh.Password = matkhau;
                kh.Email = email;
                kh.Address = diachi;
                kh.Phone = dienthoai;
                kh.DateofBirth = DateTime.Parse(ngaysinh);
                kh.IdCustomer = Convert.ToInt32(collection["id"]);

                UpdateModel(kh);
                data.SubmitChanges();
                return RedirectToAction("Index", "DichVu");
            }

Views/NguoiDung/DangKy.cshtml
@model CLEANSHOP.Models.Customer

@{
    ViewBag.Title = "DangKy";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Đăng Ký</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-10">
                <label class="control-label col-md-2" for="Name">
                    Họ Tên :
                </label>
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        @*    <div class="form-group">
                <label class="control-label col-md-2" for="Phone">
                    Số điện thoại :
                </label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                </div>
            </div>*@
        <div class="form-group">
            <div class="col-md-10">
                <label class="control-label col-md-2">

                    <strong>Số điện thoại :</strong>
                </label>
                <input class="form-control" type="text" id="Phones" name="Phone" placeholder="Nhập số điện thoại " onchange="PhoneCheck()" />
                @ViewData["nhapDT"]
            </div>
        </div>


        <div class="col-md-10">
            <p id="Status" />
        </div>


        <script>
        function PhoneCheck() {
                $("#Status").html("Checking...");
                $.post("@Url.Action("CheckPhone", "NguoiDung")",
                    {
                        userdata: $("#Phones").val()
                    },
                    function (data) {
                        if (data == 0) {
                            $("#Status").html('<font color = "Green"> Số điện thoại có thể sử dụng.</font>');
                            $("#Phones").css("border-color", "Green");
                        }
                        else {
                            $("#Status").html('<font color = "Red"> Số điện thoại đã có người sử dụng.</font>');
                            $("#Phones").css("border-color", "Red");

                        }
                    });
            }
        </script>



        <div class="form-group">
            <div class="col-md-10">
                <label class="control-label col-md-2" for="Address">
                    Địa Chỉ :
                </label>
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                @ViewData["nhapDC"]
            </div>
        </div>

        @*  <div class="form-group">
                <label class="control-label col-md-2" for="Email">
                    Email :
                </label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>*@
        <div class="form-group">
            <div class="col-md-10">
                <label class="control-label col-md-2">

                    <strong>Email :</strong>
                </label>
                <input class="form-control" type="text" id="Emaill" name="Email" placeholder="Nhập Email" onchange="GmailCheck()" />
                @ViewData["nhapEmail"]
            </div>
        </div>


        <div class="col-md-10">
            <p id="Status" />
        </div>


        <script>
        function GmailCheck() {
                $("#Status").html("Checking...");
                $.post("@Url.Action("CheckEmail", "NguoiDung")",
                    {
                        userdata: $("#Emaill").val()
                    },
                    function (data) {
                        if (data == 0) {
                            $("#Status").html('<font color = "Green"> Email có thể sử dụng.</font>');
                            $("#Emaill").css("border-color", "Green");
                        }
                        else {
                            $("#Status").html('<font color = "Red"> Email đã có người sử dụng.</font>');
                            $("#Emaill").css("border-color", "Red");

                        }
                    });
            }
        </script>



        @*    <div class="form-group">
                <label class="control-label col-md-2" for="LoginName">
                    Tên đăng nhập :
                </label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LoginName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LoginName, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <div class="col-md-10">
                <label class="control-label col-md-2">

                    <strong>Tài Khoản:</strong>
                </label>
                <input class="form-control" type="text" id="Username" name="LoginName" placeholder="Nhập tài khoản" onchange="UserCheck()" />
                @ViewData["NhapTK"]
            </div>
        </div>


        <div class="col-md-10">
            <p id="Status" />
        </div>


        <script>
            function UserCheck() {
                $("#Status").html("Checking...");
                $.post("@Url.Action("CheckUsername","NguoiDung")",
                    {
                        userdata: $("#Username").val()
                    },
                    function (data) {
                        if (data == 0) {
                            $("#Status").html('<font color = "Green"> Tài khoản có thể sử dụng.</font>');
                            $("#Username").css("border-color", "Green");
                        }
                        else {
                            $("#Status").html('<font color = "Red"> Tài khoản tồn tại.</font>');
                            $("#Username").css("border-color", "Red");

                        }
                    });
            }
        </script>




        <div class="form-group">
            <div class="col-md-10">
                <label class="control-label col-md-2" for="Password">
                    Mật khẩu :
                </label>
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <label class="control-label col-md-2" for="ConfirmPassword">
                    Xác nhận mật khẩu :
                </label>
                <input class="form-control text-box single-line input-validation-error"
                       data-val="true" data-val-required="Phải nhập mật khẩu xác nhận!"
                       id="ConfirmPassword" name="ConfirmPassword" type="password" value="" aria-
                       describedby="ConfirmPassword-error" aria-invalid="true">
                @ViewData["NhapMKXN"]
                @ViewData["MatKhauGiongNhau"]
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <label class="control-label col-md-2" for="DateofBirth">
                    Ngày sinh :
                </label>
                @Html.EditorFor(model => model.DateofBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateofBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Đăng ký" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Views/NguoiDung/DangNhap.cshtml
@model CLEANSHOP.Models.Customer

@{
    ViewBag.Title = "DangNhap";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Đăng Nhập | Đăng Ký</h2>
<link href="~/Content/dangnhap.css" rel="stylesheet" />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()



    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
   

        <hr>



        <div class="box">

            <div class="form">
                <div style="display:flex; justify-content:space-between ; margin:20px">

                    <a class="btn btn-info" style="margin:initial" href="@Url.Action("DangKy", "NguoiDung", new { @class = "form-control" })">Đăng ký</a>

                    <a class="btn btn-info" style="margin:initial ;margin-left:20px" href="/NguoiDung/LoginFB">Facebook</a>
                </div>
                <div>
                    <div class="form-group">
                        <div class="col-md-10" style="margin-bottom:20px">
                            @Html.EditorFor(model => model.LoginName, new { htmlAttributes = new { @class = "form-control", placeholder = "Tên đăng nhập" } })
                            @Html.ValidationMessageFor(model => model.LoginName, "", new { @class = "text-danger" })
                            <i></i>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-10 ">
                            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", Type = "password", placeholder = "Password", Id = "myInput" } })
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                            <i></i>
                            <input class="" type="checkbox" onclick="myFunction()" />Show
                        </div>
                    </div>

                    <p style="color:red;">@ViewBag.ThongBao</p>
                    <div class="form-group" style="padding:30px;">
                        <div class="col-md-offset-2 col-md-10" style=" margin: 0;">
                            <input type="submit" value="Đăng nhập " class="btn btn-info" style="width:100%;" />

                        </div>


                    </div>
                </div>
            </div>
        </div> <!-- card.// -->

    
    <!-- col.// -->


}


<script>
    function myFunction() {
        var x = document.getElementById("myInput");
        if (x.type === "password") {
            x.type = "text";
        } else {
            x.type = "password";
        }
    }
</script>

<p style="margin-top:30px">
    @Html.ActionLink("Về trang chủ", "Index", "DichVu")
</p>

Views/NguoiDung/DonHangCuaToi.cshtml
@model IEnumerable<CLEANSHOP.Models.Cart>
@using CLEANSHOP.Models;

@{
    ViewBag.Title = "DonHangCuaToi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Đơn hàng của tôi</h2>


<table class="table">
    <tr>
        <th>
            Tên khách hàng
        </th>
        <th>
          Ngày giao
        </th>
        <th>
            Ngày đặt
        </th>
        
        <th>
            Tổng tiền
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Customer.Name)
    </td>

    <td>
        @Html.DisplayFor(modelItem => item.DeliveryDate)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.BookingDate)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.TotalPrice)
    </td>

   
</tr>
    }

</table>
<tr>
<td colspan="5" class="text-right"><b>Tổng hóa đơn : @String.Format("{0:0,0}", @ViewBag.tongtien2) VNĐ</b></td>

</tr>

Views/NguoiDung/profile.cshtml
@model CLEANSHOP.Models.Customer

@{
    ViewBag.Title = "profile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Thông tin khách hàng</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdCustomer)

        <div class="form-group txt1">
            @* @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label>Tên</label>
            <div class="col-md-10">

                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group txt1">
            @*@Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label>số điện thoại</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group txt1">
            @*@Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label>Địa chỉ</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group txt1">
            @*@Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label>Email</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group txt1">
            @*@Html.LabelFor(model => model.LoginName, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label>Tên đăng nhập</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.LoginName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LoginName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group txt1">
            @*@Html.LabelFor(model => model.DateofBirth, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label>Ngày sinh</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateofBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateofBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group txt1">
            @*@Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label>Mật khẩu</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Về trang chủ", "Index", "DichVu")
</div>
<style>
    .txt1 {
        display: flex;
    }

        .txt1 label {
            width: 100px;
        }
</style>